[build]
command = "cd exampleSite && hugo --minify --themesDir ..\.."
publish = "exampleSite/public"
[build.environment]
HUGO_BASEURL = "https://Hugo-Doodle.netlify.app"
HUGO_THEME = "Hugo-Doodle"
HUGO_VERSION = "0.90.1"
