[build]
command = "hugo -s exampleSite --minify --gc"
publish = "exampleSite/public"
[build.environment]
HUGO_BASEURL = "https://Hugo-Doodle.netlify.app"
HUGO_THEME = "Hugo-Doodle"
HUGO_VERSION = "0.90.1"

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "default-src 'self'; font-src 'self'; frame-ancestors 'none'; frame-src 'self' https://www.youtube-nocookie.com https://i.vimeocdn.com; img-src 'self' https://i.vimeocdn.com; script-src 'strict-dynamic' localhost:1313 https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js; style-src 'self' 'unsafe-hashes' 'sha256-uZZWz17a29ItP5ba+GPU37fLKjLXV9FhFo3EYSySzDc='; base-uri 'none'; form-action 'none'; upgrade-insecure-requests; navigate-to 'none'"
Permissions-Policy = "interest-cohort=()"
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = 'nosniff'
X-Frame-Options = 'DENY'
X-XSS-Protection = '0'
[[headers]]
for = "/post/math-typesetting/index.html"
[headers.values]
Content-Security-Policy = """
font-src 'self' 'unsafe-inline';
script-src 'self';
"""
