enableInlineShortcodes = true
timeout = 30000

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[privacy]

[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disableInlineCSS = true
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true
